/* bp_cache_manifest.h -- GENERATED by tools/gen_cache_manifest.py.
 * 30 AssetBundles, 244.0 MB, from a complete UnityCache.
 *
 * bp_net.c requires every entry below under
 * <root>/files/UnityCache/Shared/<id>/<hash>/ -- non-empty __data with an
 * __info beside it -- before it disables the internet. The content hash is
 * pinned, not just the bundle name, so a content update fails the check and
 * the game stays online to fetch the new bundles.
 *
 * A bundle id may appear more than once with different hashes; Unity keeps
 * cached versions side by side and all of them are required.
 */
#ifndef BP_CACHE_MANIFEST_H
#define BP_CACHE_MANIFEST_H
static const struct { const char *id, *hash; } k_bp_cache_manifest[] = {
  { "audio", "58c6b6ac32b847134e316b3f41bff12f" },  /* 31392 bytes */
  { "audio", "ef5d29a61aaeb7d58e3d5dfd44e47255" },  /* 11149603 bytes */
  { "character-resources", "a7f7e27465c764708636141f32ba9e8e" },  /* 2772449 bytes */
  { "christmas-assets", "c717400dcee3ee6c796b5b0b0f708e03" },  /* 375487 bytes */
  { "christmas-scenes", "526228b4f1cdc93d7e78f520ed0bc66c" },  /* 5647937 bytes */
  { "christmas-variants", "330ebe05a9c215439f0306aeb2acee93" },  /* 980717 bytes */
  { "effects", "ea56f05b96be3678ce75787bb08247a5" },  /* 3246382 bytes */
  { "general", "2f41e3aa22c19cace23ae1427574fd48" },  /* 103748 bytes */
  { "halloween-assets", "93122cf6f26a2686b657488f1fdf3bf7" },  /* 467640 bytes */
  { "halloween-scenes", "ef053ac76b08620fe1c8f5268e992e66" },  /* 5715520 bytes */
  { "halloween-variants", "bed3fc81218dfb2b13937ee89cbb9b19" },  /* 880084 bytes */
  { "investigation-assets", "3d9ad15edbe11199b1c333b345142f5f" },  /* 457512 bytes */
  { "investigation-scenes", "49dd9def8ce6c3d5050c5c994d182571" },  /* 497449 bytes */
  { "investigation-variants", "fd3274b23aa3cf28c1931d514cf8244a" },  /* 360649 bytes */
  { "item-resources", "edf5c24f0218cb39388ffaf714a196d1" },  /* 317796 bytes */
  { "maps", "e43462f0d474add758f22790261f0758" },  /* 12613714 bytes */
  { "martiantrials-assets", "a7ce64403be0273500de111c4a3940bb" },  /* 5614776 bytes */
  { "martiantrials-scenes", "c43e88c9b522a12ef9a248fed499e5dc" },  /* 1787001 bytes */
  { "martiantrials-variants", "191a2d5f1821dfdb7aefa52a6dc9db2a" },  /* 3342385 bytes */
  { "music", "d8c0d4ee89c9aaf39bcf6c5fbad8fcf9" },  /* 29216732 bytes */
  { "scripts", "968d175177eff74ebdb4c3f53eb3e0d6" },  /* 33613 bytes */
  { "sfx", "e7bc6c385b6cd45e342a4606b82f7600" },  /* 2546155 bytes */
  { "sfx-ingame", "217b239cf1d06be45cdfb3339826ec14" },  /* 23218531 bytes */
  { "shared-seasonal-scenes", "27dc989a011cfc4b84ee86f3e148d3c0" },  /* 459797 bytes */
  { "shared-seasonal-variants", "05f4615551b1d5c523a576e02ffdef20" },  /* 25823 bytes */
  { "shared_stuff", "3294ee83c35cb073eaa6152751242786" },  /* 117956080 bytes */
  { "towers", "d88794637172c4699afa3820e07e69b2" },  /* 1373753 bytes */
  { "ui-common", "e1721d319b2051b4f0875b65a199c88e" },  /* 62119 bytes */
  { "ui-scenes", "59611350959509d76457b3342b93210b" },  /* 6557260 bytes */
  { "ui-variants", "a7bc86353f67430459076239b4a92d6c" },  /* 18016477 bytes */
};
#define BP_CACHE_MANIFEST_COUNT 30
#endif /* BP_CACHE_MANIFEST_H */
