/* ---------------------------------------------------------------------------
 * bp_offsets.h -- GENERATED by tools/offsets/gen_battd_offsets.py.
 * Do not hand-edit; regenerate.
 *
 *   game  libunity.so   BuildID 6d0adf1c159f63eb227752bf94f34be769d2e5b6
 *   game  libil2cpp.so  BuildID e17c4e0feebec929f83a90a8ae1edc4da7f8c541
 *   ref   libunity_sym.so / libunity2020340f1.so, Unity 2020.3.40f1 (ba48d4efcef1)
 *
 * The game ships the STOCK Android player: the reference pair has the SAME
 * BuildID and a byte-identical .text (sha256 of .text matches, 18429772 bytes).
 * Every RVA below is therefore read straight from the reference symbol table,
 * not fingerprinted.  Guard words are read from the GAME binary and verified at
 * runtime anyway, so a future update that changes the engine build disables the
 * affected patch loudly instead of writing into the wrong function.
 * MIT.
 * ------------------------------------------------------------------------- */
#ifndef BP_OFFSETS_H
#define BP_OFFSETS_H
#include <stdint.h>

typedef struct { const char *name; uint32_t rva; uint32_t size; uint32_t guard[4]; } BpSite;

/* ======================= VSYNC (pumped, NOT patched -- bp_vsync.c) ======= */
#define BP_RVA_GetVSyncCounter                    0x06ad8c4u  /* GetVSyncCounter() */
static const uint32_t BP_GUARD_GetVSyncCounter[4] = { 0xf81e0ff4u, 0xa9017bf3u, 0xb0008c13u, 0x911eb273u };
#define BP_RVA_WaitVSync                          0x06ad8fcu  /* WaitVSync(int) */
static const uint32_t BP_GUARD_WaitVSync[4] = { 0xa9be53f5u, 0xa9017bf3u, 0x2a0003f3u, 0x97ff6591u };
#define BP_RVA_GetVSyncTime                       0x06ad960u  /* GetVSyncTime(int, bool) */
static const uint32_t BP_GUARD_GetVSyncTime[4] = { 0xfc1c0fe8u, 0xf90007f8u, 0xa9015bf7u, 0xa90253f5u };
#define BP_RVA_GetFrameTimeNanos                  0x06ada8cu  /* GetFrameTimeNanos() */
static const uint32_t BP_GUARD_GetFrameTimeNanos[4] = { 0xa9bf7bf3u, 0xb0008c00u, 0x911e0000u, 0x9418631bu };
#define BP_RVA_AndroidSync                        0x0429f4cu  /* the only caller of WaitVSync */
static const uint32_t BP_GUARD_AndroidSync[4] = { 0xd10183ffu, 0x6d0423e9u, 0xa9057bf3u, 0x910003e8u };
/* WaitVSync(target): lock mutex; while (counter < target) cond_wait; unlock.
 * mutex@+0, cond@+0x28, int32 counter@+0x58 -- the same block shape the
 * lineage found in 2020.3.15f2, read here from WaitVSync's own adrp/add. */
#define BP_VSYNC_MUTEX    0x182e7acu
#define BP_VSYNC_COND     0x182e7d4u
#define BP_VSYNC_COUNTER  0x182e804u   /* int32 */
static const uint32_t BP_GUARD_WaitVSync_state[4] = { 0xb0008c14u, 0x911eb294u, 0xaa1403e0u, 0x97ea629au };  /* +0x20..+0x2c */

/* ======================= SWAPPY (statically linked in 2020.3) ============ */
/* androidUseSwappy is off in BATTD's PlayerSettings; these make sure. Swappy's
 * Java choreographer thread would wait for callbacks that cannot arrive. */
#define BP_RVA_Swappy_IsEnabledAndActive          0x0686f4cu  /* PATCH ret 0 */
static const uint32_t BP_GUARD_Swappy_IsEnabledAndActive[4] = { 0xa9bf7bf3u, 0xf0008d13u, 0x3952c668u, 0x7100051fu };
#define BP_RVA_SwappyGL_Init                      0x068715cu  /* PATCH ret */
static const uint32_t BP_GUARD_SwappyGL_Init[4] = { 0xd100c3ffu, 0xf9000bf4u, 0xa9027bf3u, 0x97ffff79u };
#define BP_RVA_Swappy_CheckDeviceSupport          0x0687220u  /* PATCH ret 0 */
static const uint32_t BP_GUARD_Swappy_CheckDeviceSupport[4] = { 0xf81d0ff6u, 0xa90153f5u, 0xa9027bf3u, 0xd0008d16u };
#define BP_RVA_Swappy_UpdateSwapInterval          0x0686fdcu  /* PATCH ret */
static const uint32_t BP_GUARD_Swappy_UpdateSwapInterval[4] = { 0xd10143ffu, 0xa9047bf3u, 0x910003e8u, 0x94004ad9u };
#define BP_RVA_Swappy_UpdateFrameInterval         0x0686facu  /* PATCH ret */
static const uint32_t BP_GUARD_Swappy_UpdateFrameInterval[4] = { 0xf81f0ffeu, 0xd00088a8u, 0xb90f1500u, 0x97f699eau };
#define BP_RVA_SwappyGL_Swap                      0x0687110u  /* record only */
static const uint32_t BP_GUARD_SwappyGL_Swap[4] = { 0xf81e0ff4u, 0xa9017bf3u, 0xaa0103f3u, 0xaa0003f4u };
#define BP_RVA_Swappy_GetRequiredSwapIntervalNS   0x0687084u  /* record only */
static const uint32_t BP_GUARD_Swappy_GetRequiredSwapIntervalNS[4] = { 0xa9bf7bf3u, 0xaa0003f3u, 0x97ffffb0u, 0x360001e0u };

/* ======================= ENGINE PATCHES ================================== */
#define BP_RVA_APK_CanHandle                      0x069eadcu  /* ret 0: no APK here; stops a zip scan on every open */
static const uint32_t BP_GUARD_APK_CanHandle[4] = { 0xd10143ffu, 0xf9001bf4u, 0xa9047bf3u, 0xd53bd054u };
#define BP_RVA_GetAndroidAudioOutputType          0x06a270cu  /* ret 2 = OpenSL (1 = AudioTrack via Java) */
static const uint32_t BP_GUARD_GetAndroidAudioOutputType[4] = { 0xd10183ffu, 0xf90013f8u, 0xa9035bf7u, 0xa90453f5u };
#define BP_RVA_ApiLevel                           0x068d4f0u  /* ret 33 */
static const uint32_t BP_GUARD_ApiLevel[4] = { 0xf81e0ff4u, 0xa9017bf3u, 0xb0008cf4u, 0xb94d4693u };
#define BP_RVA_DVM_GetInternetReachability        0x069286cu  /* answered from nifm */
static const uint32_t BP_GUARD_DVM_GetInternetReachability[4] = { 0xd10083ffu, 0xa9017bf3u, 0x910003e0u, 0x910003f3u };
#define BP_RVA_GetPhysicalMemoryMB                0x068f038u  /* hooked -> config.txt memory_mb; the games art-quality gate needs >= 1536 */
static const uint32_t BP_GUARD_GetPhysicalMemoryMB[4] = { 0xf81f0ffeu, 0x9400ba49u, 0xf9400408u, 0xd354fd00u };

/* ======================= ENGINE CLOCK (bp_tmclock.c) ===================== */
#define BP_RVA_TimeManager_Update                 0x042a2bcu  /* detoured onto a monotonic clock; 15-word prologue guard */
static const uint32_t BP_GUARD_TimeManager_Update[15] = { 0x6dbd23e9u, 0xf9000bf4u, 0xa9027bf3u, 0xf9406408u, 0xb940d009u, 0x3943e00au, 0x91000508u, 0x11000529u, 0xf9006408u, 0xb900d009u, 0x340000aau, 0xa9427bf3u, 0xf9400bf4u, 0x6cc323e9u, 0xd65f03c0u };
#define BP_RVA_TimeManager_SetTimeScale           0x042a750u  /* fallback forwarding */
static const uint32_t BP_GUARD_TimeManager_SetTimeScale[4] = { 0xd10283ffu, 0xf90043f4u, 0xa9097bf3u, 0xd53bd053u };
#define BP_RVA_GetTimeManager                     0x042a978u  /* TimeManager instance */
static const uint32_t BP_GUARD_GetTimeManager[4] = { 0xf81f0ffeu, 0x32000be0u, 0x9400e755u, 0xf84107feu };
#define BP_RVA_EnableFrameTimeTracker             0x06adb00u  /* PATCH ret -- the 2020.3 frame-2 Looper deadlock */
static const uint32_t BP_GUARD_EnableFrameTimeTracker[4] = { 0xd10083ffu, 0xa9017bf3u, 0x910023e0u, 0x910023f3u };
#define BP_RVA_GetTimeSinceStartup                0x0558c7cu  /* diagnostic */
static const uint32_t BP_GUARD_GetTimeSinceStartup[4] = { 0xa9bf7bf3u, 0xf0009628u, 0xf943a113u, 0xb5000133u };
/* TimeManager::Update prologue, field offsets and body entry, read from the
 * disassembly.  This build uses the 0x30 frame saving d9/d8 -- the
 * 2020.3.39f1 (badpiggies_nx) shape, NOT 2020.3.15f2's 0x20/d8-only frame,
 * so that trampoline transfers unchanged. */
#define BP_TM_BODY_OFF                0x3cu
#define BP_TM_BODY_WORD               0x4ea01c08u   /* mov v8.16b, v0.16b */
#define BP_TM_EPILOGUE_OFF            0x2cu   /* shared exit: ldp x19,x30,[sp,#0x20] */
#define BP_TM_FIELD_FRAMECOUNT        0xc8    /* u64 */
#define BP_TM_FIELD_AUX               0xd0    /* u32 */
#define BP_TM_FIELD_PAUSE             0xf8    /* u8  */
#define BP_TM_PROLOGUE_WORDS  3u
static const uint32_t BP_TM_PROLOGUE[3] = { 0x6dbd23e9u, 0xf9000bf4u, 0xa9027bf3u };


/* ======================= TIME icall bindings (all 29 this build registers) ======================= */
static const BpSite BP_TIME_SITES[] = {
  { "get_captureDeltaTime", 0x0725e90u,  20u, { 0xf81f0ffeu, 0x97f412b9u, 0xbd40d800u, 0xf84107feu } },
  { "get_deltaTime", 0x0725c9cu,  20u, { 0xf81f0ffeu, 0x97f41336u, 0xbd40a800u, 0xf84107feu } },
  { "get_fixedDeltaTime", 0x0725d5cu,  20u, { 0xf81f0ffeu, 0x97f41306u, 0xbd404800u, 0xf84107feu } },
  { "get_fixedTime", 0x0725cb0u,  24u, { 0xf81f0ffeu, 0x97f41331u, 0xfd401800u, 0x1e624000u } },
  { "get_fixedTimeAsDouble", 0x0725cc8u,  20u, { 0xf81f0ffeu, 0x97f4132bu, 0xfd401800u, 0xf84107feu } },
  { "get_fixedUnscaledDeltaTime", 0x0725d48u,  20u, { 0xf81f0ffeu, 0x97f4130bu, 0xbd404c00u, 0xf84107feu } },
  { "get_fixedUnscaledTime", 0x0725d08u,  24u, { 0xf81f0ffeu, 0x97f4131bu, 0xfd402000u, 0x1e624000u } },
  { "get_fixedUnscaledTimeAsDouble", 0x0725d20u,  20u, { 0xf81f0ffeu, 0x97f41315u, 0xfd402000u, 0xf84107feu } },
  { "get_frameCount", 0x0725e40u,  20u, { 0xf81f0ffeu, 0x97f412cdu, 0xb940c800u, 0xf84107feu } },
  { "get_inFixedTimeStep", 0x0725ec4u,  20u, { 0xf81f0ffeu, 0x97f412acu, 0x3943e400u, 0xf84107feu } },
  { "get_maximumDeltaTime", 0x0725d90u,  20u, { 0xf81f0ffeu, 0x97f412f9u, 0xbd410000u, 0xf84107feu } },
  { "get_maximumParticleDeltaTime", 0x0725dd8u,  20u, { 0xf81f0ffeu, 0x97f412e7u, 0xbd410400u, 0xf84107feu } },
  { "get_realtimeSinceStartup", 0x0725e68u,  24u, { 0xf81f0ffeu, 0x97f412c3u, 0x97f41273u, 0x1e624000u } },
  { "get_realtimeSinceStartupAsDouble", 0x0725e80u,  16u, { 0xf81f0ffeu, 0x97f412bdu, 0xf84107feu, 0x17f4126cu } },
  { "get_renderedFrameCount", 0x0725e54u,  20u, { 0xf81f0ffeu, 0x97f412c8u, 0xb940d000u, 0xf84107feu } },
  { "get_smoothDeltaTime", 0x0725dc4u,  20u, { 0xf81f0ffeu, 0x97f412ecu, 0xbd40b000u, 0xf84107feu } },
  { "get_time", 0x0725c34u,  24u, { 0xf81f0ffeu, 0x97f41350u, 0xfd404800u, 0x1e624000u } },
  { "get_timeAsDouble", 0x0725c4cu,  20u, { 0xf81f0ffeu, 0x97f4134au, 0xfd404800u, 0xf84107feu } },
  { "get_timeScale", 0x0725e0cu,  20u, { 0xf81f0ffeu, 0x97f412dau, 0xbd40fc00u, 0xf84107feu } },
  { "get_timeSinceLevelLoad", 0x0725c60u,  32u, { 0xf81f0ffeu, 0x97f41345u, 0xfd404800u, 0xfd407801u } },
  { "get_timeSinceLevelLoadAsDouble", 0x0725c80u,  28u, { 0xf81f0ffeu, 0x97f4133du, 0xfd404800u, 0xfd407801u } },
  { "get_unscaledDeltaTime", 0x0725d34u,  20u, { 0xf81f0ffeu, 0x97f41310u, 0xbd40ac00u, 0xf84107feu } },
  { "get_unscaledTime", 0x0725cdcu,  24u, { 0xf81f0ffeu, 0x97f41326u, 0xfd405000u, 0x1e624000u } },
  { "get_unscaledTimeAsDouble", 0x0725cf4u,  20u, { 0xf81f0ffeu, 0x97f41320u, 0xfd405000u, 0xf84107feu } },
  { "set_captureDeltaTime", 0x0725ea4u,  32u, { 0xfc1f0fe8u, 0xf90007feu, 0x4ea01c08u, 0x97f412b2u } },
  { "set_fixedDeltaTime", 0x0725d70u,  32u, { 0xfc1f0fe8u, 0xf90007feu, 0x4ea01c08u, 0x97f412ffu } },
  { "set_maximumDeltaTime", 0x0725da4u,  32u, { 0xfc1f0fe8u, 0xf90007feu, 0x4ea01c08u, 0x97f412f2u } },
  { "set_maximumParticleDeltaTime", 0x0725decu,  32u, { 0xfc1f0fe8u, 0xf90007feu, 0x4ea01c08u, 0x97f412e0u } },
  { "set_timeScale", 0x0725e20u,  32u, { 0xfc1f0fe8u, 0xf90007feu, 0x4ea01c08u, 0x97f412d3u } },
};

/* ======================= INPUT icall bindings ======================= */
static const BpSite BP_INPUT_SITES[] = {
  { "GetAxisRaw", 0x0354708u, 184u, { 0xd10203ffu, 0xfd002be8u, 0xf9002ff6u, 0xa90653f5u } },
  { "GetButtonDown", 0x0354960u, 176u, { 0xd10203ffu, 0xa9055bf7u, 0xa90653f5u, 0xa9077bf3u } },
  { "GetKeyDownInt", 0x035434cu,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetKeyInt", 0x0353e1cu,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetKeyUpInt", 0x03540c0u,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetMouseButton", 0x0354bb0u,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetMouseButtonDown", 0x0354ca8u,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetMouseButtonUp", 0x0354d94u,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetTouch_Injected", 0x035500cu,  80u, { 0xd101c3ffu, 0xa9067bf3u, 0xaa0103f3u, 0x910023e8u } },
  { "get_compositionCursorPos_Injected", 0x03556c4u,  28u, { 0xa9bf7bf3u, 0xaa0003f3u, 0x94036025u, 0xf9409c08u } },
  { "get_compositionString", 0x0355624u, 140u, { 0xd10143ffu, 0xf9001bf4u, 0xa9047bf3u, 0xd53bd054u } },
  { "get_imeCompositionMode", 0x03555f8u,  20u, { 0xf81f0ffeu, 0x94036059u, 0xb9414400u, 0xf84107feu } },
  { "get_mousePosition_Injected", 0x035545cu,  80u, { 0xd100c3ffu, 0xa9027bf3u, 0xaa0003f3u, 0x910003e8u } },
  { "get_mousePresent", 0x0355730u,  20u, { 0xf81f0ffeu, 0x940cf672u, 0x12000000u, 0xf84107feu } },
  { "get_mouseScrollDelta_Injected", 0x0355538u,  68u, { 0xd100c3ffu, 0xa9027bf3u, 0xaa0003f3u, 0x910023e8u } },
  { "get_touchCount", 0x0355744u,  16u, { 0xf81f0ffeu, 0x940cfb20u, 0xf84107feu, 0xd65f03c0u } },
  { "get_touchSupported", 0x035577cu,  20u, { 0xf81f0ffeu, 0x9403687fu, 0x12000000u, 0xf84107feu } },
  { "set_compositionCursorPos_Injected", 0x03556e0u,  28u, { 0xa9bf7bf3u, 0xaa0003f3u, 0x9403601eu, 0xf9400268u } },
  { "set_imeCompositionMode", 0x035560cu,  24u, { 0xa9bf7bf3u, 0x2a0003f3u, 0x94036053u, 0xb9014413u } },
  { "set_multiTouchEnabled", 0x03557a4u,  12u, { 0x72001c1fu, 0x1a9f07e0u, 0x140cfbc9u, 0xf81f0ffeu } },  /* NOT hookable: 12 bytes < 16-byte stub */
};

/* ======================= SCREEN icall bindings ======================= */
static const BpSite BP_SCREEN_SITES[] = {
  { "GetScreenOrientation", 0x06d61d8u,  24u, { 0xf81f0ffeu, 0x97f77ff9u, 0xf9400008u, 0xf9408d01u } },
  { "get_currentResolution_Injected", 0x06d627cu,  40u, { 0xa9bf7bf3u, 0xaa0003f3u, 0x97f77fcfu, 0xf9400008u } },
  { "get_dpi", 0x06d61a0u,  24u, { 0xf81f0ffeu, 0x97f78007u, 0xf9400008u, 0xf9407101u } },
  { "get_fullScreenMode", 0x06d62e0u,  24u, { 0xf81f0ffeu, 0x97f77fb7u, 0xf9400008u, 0xf9407901u } },
  { "get_height", 0x06d6188u,  24u, { 0xf81f0ffeu, 0x97f7800du, 0xf9400008u, 0xf9406101u } },
  { "get_safeArea_Injected", 0x06d6310u,  40u, { 0xa9bf7bf3u, 0xaa0003f3u, 0x97f77faau, 0xf9400008u } },
  { "get_sleepTimeout", 0x06d61f0u,  24u, { 0xf81f0ffeu, 0x97f77ff3u, 0xf9400008u, 0xf9404d01u } },
  { "get_width", 0x06d6170u,  24u, { 0xf81f0ffeu, 0x97f78013u, 0xf9400008u, 0xf9405d01u } },
  { "set_sleepTimeout", 0x06d6208u,  32u, { 0xa9bf7bf3u, 0x2a0003f3u, 0x97f77fecu, 0xf9400008u } },
};
#define BP_NSITES(a) ((int)(sizeof(a) / sizeof((a)[0])))

/* ======================= FMOD OpenSL output ============================== */
#define BP_RVA_FMOD_OutputOpenSL_init             0x1279c64u  /* four-site buffer-geometry patch */
static const uint32_t BP_GUARD_FMOD_OutputOpenSL_init[4] = { 0xd10303ffu, 0xa9085ff8u, 0xa90957f6u, 0xa90a4ff4u };
/* The four sites sit at exactly the same offsets from the function start as in
 * 2020.3.15f2 (bloonspop_nx) and in bouncemasters_nx: 2020.3's FMOD really is
 * instruction-identical across these builds.  Verified word-for-word below. */
/* bp_patches.c consumes these guards as `const uint32_t g[4] = { MACRO }`,
 * i.e. ONE word plus three implicit zeros, and patch_guard1 checks one word. */
#define BP_RVA_FMOD_PERIOD_LDR          0x1279dc0u  /* +0x15c: ldr w9, [x19, #0x3f8] */
#define BP_GUARD_FMOD_PERIOD_LDR        0xb943fa69u  /* ldr w9,[x19,#0x3f8] -> movz w9,#BP_AUDIO_PERIOD_FRAMES */
#define BP_RVA_FMOD_PERIOD_CBZ          0x1279dc4u  /* +0x160: cbz w9, #0x1279de8 */
#define BP_GUARD_FMOD_PERIOD_CBZ        0x34000129u  /* cbz w9              -> str w9,[x19,#0x3f8] */
#define BP_RVA_FMOD_BUFGEOM_BRANCH      0x1279de4u  /* +0x180: b.ls #0x1279df4 */
#define BP_GUARD_FMOD_BUFGEOM_BRANCH    0x54000089u  /* b.ls                -> b (same target) */
#define BP_RVA_FMOD_BUFCOUNT            0x1279e40u  /* +0x1dc: udiv w9, w10, w9 */
#define BP_GUARD_FMOD_BUFCOUNT          0x1ac90949u  /* udiv w9,w10,w9      -> movz w9,#BP_AUDIO_UPFRONT_BUFFERS */
#define BP_FMOD_PERIOD_FIELD_OFF 0x3f8u

/* ======================= unitytls (CA install, bp_net.c) ================= */
#define BP_RVA_unitytls_errorstate_create         0x0b9fc80u  /* fresh errorstate per cert */
static const uint32_t BP_GUARD_unitytls_errorstate_create[4] = { 0x529f58e0u, 0x72a0d960u, 0xaa1f03e1u, 0xd65f03c0u };
#define BP_RVA_unitytls_x509list_append_der       0x0ba0448u  /* the call Android's own trust store uses */
static const uint32_t BP_GUARD_unitytls_x509list_append_der[4] = { 0xf81c0ff8u, 0xa9015bf7u, 0xa90253f5u, 0xa9037bf3u };
#define BP_RVA_unitytls_x509list_append_pem       0x0ba0554u  /* NUL-terminated fallback only */
static const uint32_t BP_GUARD_unitytls_x509list_append_pem[4] = { 0xa9ba6ffcu, 0xa90167fau, 0xa9025ff8u, 0xa90357f6u };
#define BP_RVA_unitytls_x509list_get_x509         0x0ba01f4u  /* count the published list */
static const uint32_t BP_GUARD_unitytls_x509list_get_x509[4] = { 0xf81d0ff6u, 0xa90153f5u, 0xa9027bf3u, 0xaa0203f5u };
#define BP_RVA_unitytls_x509verify_default_ca_get 0x0ba17b4u  /* read the global list */
static const uint32_t BP_GUARD_unitytls_x509verify_default_ca_get[4] = { 0xb0006528u, 0xf9459109u, 0xb4000089u, 0xaa0003e1u };
#define BP_RVA_unitytls_default_ca_enter_sync     0x0ba17d4u  /* claim the global list */
static const uint32_t BP_GUARD_unitytls_default_ca_enter_sync[4] = { 0xf81e0ff4u, 0xa9017bf3u, 0xb0006008u, 0xf9464508u };
#define BP_RVA_unitytls_default_ca_exit_sync      0x0ba1878u  /* publish (only with a clean errorstate) */
static const uint32_t BP_GUARD_unitytls_default_ca_exit_sync[4] = { 0xa9be53f5u, 0xa9017bf3u, 0xb0006008u, 0xf9464508u };
#define BP_RVA_unitytls_x509_export_der           0x0ba0084u  /* BP_TLS_VERIFY_DIAG: save refused chains */
static const uint32_t BP_GUARD_unitytls_x509_export_der[4] = { 0xa9bd5bf7u, 0xa90153f5u, 0xa9027bf3u, 0xaa0303f4u };
/* Two unitytls_x509verify_explicit_ca overloads exist. This is the one
 * unitytls_x509verify_default_ca actually tail-calls (resolved from its own
 * branch at 0x0ba5378), i.e. the one that reaches mbedtls_x509_crt_verify. */
#define BP_RVA_unitytls_x509verify_explicit_ca    0x0ba083cu  /* size 700 */
static const uint32_t BP_GUARD_unitytls_x509verify_explicit_ca[4] = { 0xa9ba6ffcu, 0xa90167fau, 0xa9025ff8u, 0xa90357f6u };
#define BP_RVA_unitytls_x509verify_default_ca     0x0ba5068u  /* replaced by the instrumented verifier */
static const uint32_t BP_GUARD_unitytls_x509verify_default_ca[4] = { 0xd10303ffu, 0xa9066ffcu, 0xa90767fau, 0xa9085ff8u };

/* ======================= GC (derived from the GAME's libil2cpp.so) ======== */
/* derive_gc_bridge.py + derive_gc_threads.py, run against BATTD's own
 * libil2cpp.so -- no reference needed, these are Boehm statics. */
#define GC_START_ACK_OFF      0x2df06d8u  /* restart-ack gate            */
#define GC_SUSPEND_SIG_OFF    0x2df06dcu  /* GC_sig_suspend              */
#define GC_RESTART_SIG_OFF    0x2df06e0u  /* GC_sig_thr_restart          */
#define GC_ACK_SEM_OFF        0x2e01240u  /* GC_suspend_ack_sem (sem_t/void*) */
typedef struct { uint32_t off; uint32_t word; const char *what; } GcGuard;
#define BP_GC_GUARDS_INIT { \
  { 0x09a6e1cu, 0xd0012248u, "GC_sig_suspend: adrp x8, #0x2df0000" }, \
  { 0x09a6e20u, 0xb946dd08u, "GC_sig_suspend: ldr w8, [x8, #0x6dc]" }, \
  { 0x09a6eccu, 0xd0012248u, "gate: adrp x8, #0x2df0000" }, \
  { 0x09a6ed0u, 0xb946d908u, "gate: ldr w8, [x8, #0x6d8]" }, \
  { 0x09a6f04u, 0xf00122c0u, "ack_sem: adrp x0, #0x2e01000" }, \
  { 0x09a6f08u, 0x91090000u, "ack_sem: add x0, x0, #0x240" }, \
  { 0x09a6f4cu, 0xd0012248u, "gate: adrp x8, #0x2df0000" }, \
  { 0x09a6f50u, 0xb946d908u, "gate: ldr w8, [x8, #0x6d8]" }, \
  { 0x09a6f58u, 0xf00122c0u, "ack_sem: adrp x0, #0x2e01000" }, \
  { 0x09a6f5cu, 0x91090000u, "ack_sem: add x0, x0, #0x240" }, \
  { 0x09a6f84u, 0xd0012248u, "GC_sig_thr_restart: adrp x8, #0x2df0000" }, \
  { 0x09a6f88u, 0xb946e108u, "GC_sig_thr_restart: ldr w8, [x8, #0x6e0]" }, \
  { 0x09a6fecu, 0xd0012258u, "GC_sig_suspend: adrp x24, #0x2df0000" }, \
  { 0x09a7028u, 0xb946df01u, "GC_sig_suspend: ldr w1, [x24, #0x6dc]" }, \
  { 0x09a7104u, 0xd00122d5u, "ack_sem: adrp x21, #0x2e01000" }, \
  { 0x09a710cu, 0x910902b5u, "ack_sem: add x21, x21, #0x240" }, \
  { 0x09a71b0u, 0xd00122d4u, "ack_sem: adrp x20, #0x2e01000" }, \
  { 0x09a71bcu, 0x91090294u, "ack_sem: add x20, x20, #0x240" }, \
  { 0x09a7248u, 0xb0012257u, "gate: adrp x23, #0x2df0000" }, \
  { 0x09a724cu, 0xb0012258u, "GC_sig_thr_restart: adrp x24, #0x2df0000" }, \
  { 0x09a7264u, 0xb946dae8u, "gate: ldr w8, [x23, #0x6d8]" }, \
  { 0x09a7280u, 0xb946e301u, "GC_sig_thr_restart: ldr w1, [x24, #0x6e0]" }, \
  { 0x09a7348u, 0xb0012255u, "GC_sig_suspend: adrp x21, #0x2df0000" }, \
  { 0x09a734cu, 0xb946dea8u, "GC_sig_suspend: ldr w8, [x21, #0x6dc]" }, \
  { 0x09a7360u, 0xb0012254u, "GC_sig_thr_restart: adrp x20, #0x2df0000" }, \
  { 0x09a7364u, 0xb946e289u, "GC_sig_thr_restart: ldr w9, [x20, #0x6e0]" }, \
  { 0x09a7380u, 0xd00122c0u, "ack_sem: adrp x0, #0x2e01000" }, \
  { 0x09a7384u, 0x91090000u, "ack_sem: add x0, x0, #0x240" }, \
  { 0x09a73c0u, 0xb946dea0u, "GC_sig_suspend: ldr w0, [x21, #0x6dc]" }, \
  { 0x09a73e4u, 0xb946e280u, "GC_sig_thr_restart: ldr w0, [x20, #0x6e0]" }, \
}
#define GC_THREADS_OFF        0x2dfea48u  /* GC_threads[]                */
#define GC_THREADS_BUCKETS    256
#define GC_THR_NEXT_OFF       0x0
#define GC_THR_ID_OFF         0x8
#define GC_THR_LASTSTOP_OFF   0x10   /* stop_info.last_stop_count */
#define GC_THR_STACKPTR_OFF   0x18   /* stop_info.stack_ptr       */
#define GC_STOP_COUNT_OFF     0x2dfea28u  /* GC_stop_count               */
#define BP_GC_THREAD_GUARDS_INIT { \
  { 0x09a6fe4u, 0x912922d6u, "GC_threads base (add)" }, \
  { 0x09a6ff4u, 0xf8757adau, "bucket load" }, \
  { 0x09a6ffcu, 0xf9400740u, "p->id (pthread_kill arg)" }, \
  { 0x09a7018u, 0xf9400b48u, "p->stop_info.last_stop_count" }, \
  { 0x09a701cu, 0xf94516e9u, "GC_stop_count" }, \
  { 0x09a7058u, 0xf940035au, "p->next" }, \
  { 0x09a7064u, 0xf10402bfu, "bucket count" }, \
  { 0x09a62acu, 0xf9400f95u, "GC_push_all_stacks: lo = p->stop_info.stack_ptr" }, \
  { 0x09a62d0u, 0xb40005d5u, "cbz lo -> abort(sp not set)" }, \
}


/* PasswordGenerator.GetPassword(int version) in the GAME's libil2cpp.
 * Probed (not replaced) by battd_save_probe.c to log the real save
 * password -- see tools/battd_save.py for why that is the one missing
 * piece of the save format. */
#define BP_RVA_GetPassword 0x0CCF74Cu
static const uint32_t BP_GUARD_GetPassword[4] = { 0xf81d0ff5u, 0xa9014ff4u, 0xa9027bfdu, 0x910083fdu };

#endif /* BP_OFFSETS_H */
