/* ---------------------------------------------------------------------------
 * bp_patch_granularity.h -- GENERATED by tools/offsets/gen_battd_granularity.py.
 * Do not hand-edit; regenerate.
 *
 * Moves Unity 2020.3.40f1's block allocator from 256 MB regions to 64 MB, for
 * BATTD's libunity.so (BuildID 6d0adf1c159f63eb227752bf94f34be769d2e5b6).
 *
 * DERIVATION. The game ships the stock Android player, so every site is
 * attributed directly by symbol from libunity_sym.so rather than fingerprinted.
 * Detection and transform rules are bloonspop_nx's, unchanged, including the
 * three ways 2020.3 differs from the 2021+/Unity 6 tables:
 *   - level 1 of the region index is `lsr #28 ; asr #12` (== ptr>>40), so
 *     rewriting the lsr #28 moves BOTH levels -- there are no separate sites;
 *   - several sites encode 256 MB as ORR bitmask immediates;
 *   - the 255-region walk-back constant is built with orr+movk, and BOTH
 *     words are rewritten (rewriting only the movk gives -1023, not -255).
 *
 * VERIFY-FIRST, ALL-OR-NOTHING (bp_patches.c). MUST equal MMAP_ARENA_ALIGN.
 * MIT.
 * ------------------------------------------------------------------------- */
#ifndef BP_PATCH_GRANULARITY_H
#define BP_PATCH_GRANULARITY_H
#include <stdint.h>

#define BP_REGION_GRANULARITY_MB 64u

typedef struct { uint32_t rva; uint32_t from; uint32_t to; const char *what; } BpPatchWord;

static const BpPatchWord BP_GRANULARITY_WORDS[] = {
  /*  0 */ { 0x045ba1cu, 0x32006fe9u, 0x320067e9u, "LocalLowLevelAllocator::ReserveMemoryBlock +0x9c" },  /* orrimm   mov w9, #0xfffffff -> mov w9, #0x3ffffff */
  /*  1 */ { 0x045ba24u, 0x92648d36u, 0x92669536u, "LocalLowLevelAllocator::ReserveMemoryBlock +0xa4" },  /* andimm   and x22, x9, #0xfffffffff0000000 -> and x22, x9, #0xfffffffffc000000 */
  /*  2 */ { 0x045c7b0u, 0xd35cfc33u, 0xd35afc33u, "MemoryManager::VirtualAllocator::MarkMemoryBlocks +0x10" },  /* ubfm     lsr x19, x1, #0x1c -> lsr x19, x1, #0x1a */
  /*  3 */ { 0x045c7b4u, 0xd35cfd15u, 0xd35afd15u, "MemoryManager::VirtualAllocator::MarkMemoryBlocks +0x14" },  /* ubfm     lsr x21, x8, #0x1c -> lsr x21, x8, #0x1a */
  /*  4 */ { 0x045c82cu, 0x320403e8u, 0x320603e8u, "MemoryManager::VirtualAllocator::ReserveMemoryBlock +0x24" },  /* orrimm   mov w8, #0x10000000 -> mov w8, #0x4000000 */
  /*  5 */ { 0x045ca24u, 0xd35cfc2cu, 0xd35afc2cu, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x0" },  /* ubfm     lsr x12, x1, #0x1c -> lsr x12, x1, #0x1a */
  /*  6 */ { 0x045ca34u, 0x92648c28u, 0x92669428u, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x10" },  /* andimm   and x8, x1, #0xfffffffff0000000 -> and x8, x1, #0xfffffffffc000000 */
  /*  7 */ { 0x045ca3cu, 0xd35c9c2au, 0xd35a942au, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x18" },  /* ubfm     ubfx x10, x1, #0x1c, #0xc -> ubfx x10, x1, #0x1a, #0xc */
  /*  8 */ { 0x045ca50u, 0xb25c6febu, 0xb25e77ebu, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x2c" },  /* orrimm   mov x11, #-0x1000000000 -> mov x11, #-0x400000000 */
  /*  9 */ { 0x045ca54u, 0xf2a2000bu, 0xf2a0800bu, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x30" },  /* movwide  movk x11, #0x1000, lsl #16 -> movk x11, #0x400, lsl #16 */
  /* 10 */ { 0x045ca90u, 0xcb0a7108u, 0xcb0a6908u, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x6c" },  /* sublsl   sub x8, x8, x10, lsl #28 -> sub x8, x8, x10, lsl #26 */
  /* 11 */ { 0x045caa8u, 0xd35cfc28u, 0xd35afc28u, "MemoryManager::VirtualAllocator::GetBlockInfoFromPointer +0x0" },  /* ubfm     lsr x8, x1, #0x1c -> lsr x8, x1, #0x1a */
  /* 12 */ { 0x045cabcu, 0xd35c9c29u, 0xd35a9429u, "MemoryManager::VirtualAllocator::GetBlockInfoFromPointer +0x14" },  /* ubfm     ubfx x9, x1, #0x1c, #0xc -> ubfx x9, x1, #0x1a, #0xc */
  /* 13 */ { 0x045e198u, 0xd35cfc28u, 0xd35afc28u, "MemoryManager::GetAllocatorContainingPtr +0xc" },  /* ubfm     lsr x8, x1, #0x1c -> lsr x8, x1, #0x1a */
  /* 14 */ { 0x045e1b4u, 0xd35c9e89u, 0xd35a9689u, "MemoryManager::GetAllocatorContainingPtr +0x28" },  /* ubfm     ubfx x9, x20, #0x1c, #0xc -> ubfx x9, x20, #0x1a, #0xc */
  /* 15 */ { 0x045e754u, 0x320403e0u, 0x320603e0u, "AtomicPageAllocator::AllocatePage +0x48" },  /* orrimm   mov w0, #0x10000000 -> mov w0, #0x4000000 */
  /* 16 */ { 0x045edc4u, 0x32006feau, 0x320067eau, "BucketAllocator::BucketAllocator +0x84" },  /* orrimm   mov w10, #0xfffffff -> mov w10, #0x3ffffff */
  /* 17 */ { 0x045edd4u, 0x92648d01u, 0x92669501u, "BucketAllocator::BucketAllocator +0x94" },  /* andimm   and x1, x8, #0xfffffffff0000000 -> and x1, x8, #0xfffffffffc000000 */
  /* 18 */ { 0x0460c4cu, 0x320403e9u, 0x320603e9u, "DynamicHeapAllocator::DynamicHeapAllocator +0x58" },  /* orrimm   mov w9, #0x10000000 -> mov w9, #0x4000000 */
  /* 19 */ { 0x04610bcu, 0x32006feau, 0x320067eau, "DynamicHeapAllocator::RequestLargeAllocMemory +0x90" },  /* orrimm   mov w10, #0xfffffff -> mov w10, #0x3ffffff */
  /* 20 */ { 0x04610c4u, 0x92648d36u, 0x92669536u, "DynamicHeapAllocator::RequestLargeAllocMemory +0x98" },  /* andimm   and x22, x9, #0xfffffffff0000000 -> and x22, x9, #0xfffffffffc000000 */
};
#define BP_GRANULARITY_WORDS_N ((int)(sizeof(BP_GRANULARITY_WORDS) / sizeof(BP_GRANULARITY_WORDS[0])))

#endif /* BP_PATCH_GRANULARITY_H */
